### ISSUE TITLE
chromeデスクトップでメニューが表示されません

### ISSUE THREAD

**Issue by hiraly** [yondako/yondako#208]
- mac
- chrome

デスクトップサイズだとメニューが表示されません。
ただし、画面を小さくすると下部メニューが出現します。

<img width="1476" alt="スクリーンショット 2024-10-23 8 41 05" src="https://github.com/user-attachments/assets/cc7d3f87-603c-4499-b272-713d82732071">

**Comment by arrow2nd** [comment]
ありがとうございます！

色々なウィンドウサイズで検証してみましたが、手元で再現することができませんでした…
こちらの現象はまだ発生していますでしょうか…？

もし、引き続き発生していましたら

- お使いの mac のモデル
- 表示しているディスプレイの情報 (内蔵のものや、高解像度の外部ディスプレイ使っているなど)

を教えていただけますと幸いです 🙏

**Comment by hiraly** [comment]
## 発生環境

- MacbookAir M2 : MacOs 14.6.1（23G93）
- Chrome : バージョン: 130.0.6723.58（Official Build） （arm64） 

## 追加情報

- navタグにhidden属性がついてました
  <img width="1609" alt="スクリーンショット 2024-10-24 10 01 19" src="https://github.com/user-attachments/assets/812fc1f0-b80a-4b4b-a81d-edd6af7373a1">

- 以下のブラウザで同じアカウントでログインしたところ、再現しませんでした（同じディスプレイサイズで左メニューが表示された）
  - safari
  - chrome シークレットモード

ってことで、chrome extention が悪さしてる可能性が高いかもです！

**Comment by hiraly** [comment]
[ダークテーマ & 夜勤モード](https://chromewebstore.google.com/detail/%E3%83%80%E3%83%BC%E3%82%AF%E3%83%86%E3%83%BC%E3%83%9E-%E5%A4%9C%E5%8B%A4%E3%83%A2%E3%83%BC%E3%83%89/gjjbmfigjpgnehjioicaalopaikcnheo?hl=ja)
このエクステンションをオフにしたら直りました。お騒がせしました！

**Comment by arrow2nd** [comment]
拡張機能が原因というパターンは思いつきませんでした…！
解決されたようで良かったです 👍️
